// Shared, language-agnostic extraction of a short human doc summary for a symbol
// or module. The graph already knows *what* calls *what*; a one-line doc captures a
// little of *why* — the intent the code itself never states — and feeds both FTS
// (so a phrase query matches the prose) and the rendered slice (a summary line).
//
// Everything here is best-effort text scanning: over- or under-capturing only changes
// a hint, never a compiler-verified edge. Summaries are normalized to a single first
// line/sentence and capped, so a docstring never blows the render budget.

const MAX_DOC = 200;

// Leading comments that are tooling directives or boilerplate, not documentation.
const DOC_NOISE =
  /^(eslint|tslint|prettier|istanbul|c8|coverage|biome|oxlint|noqa|pylint|mypy|flake8|fmt:|type:\s*ignore|ts-|@ts-|\/?\/?\/?\s*<reference|spdx-|copyright|license\b|all rights reserved|generated by|do not edit|@author\b|@license\b)/i;

/**
 * Clean a raw comment/docstring block into a single short summary line, or undefined
 * if it carries no real prose (empty, a tooling directive, or license boilerplate).
 */
export function normalizeDoc(raw: string): string | undefined {
  if (!raw) return undefined;
  let s = raw
    .replace(/\r/g, "")
    .replace(/^\s*\/\*\*?/, "") // opening /* or /**
    .replace(/\*\/\s*$/, ""); // closing */

  s = s
    .split("\n")
    .map((l) =>
      l
        .replace(/^\s*\*\s?/, "") // jsdoc leading "* "
        .replace(/^\s*(\/\/\/?|#+|--+|;+|"""|''')\s?/, "") // line-comment / docstring markers
        .replace(/("""|''')\s*$/, "")
        .trim(),
    )
    .join("\n")
    .trim();

  // Drop a JSDoc/rst tag section (@param, @returns, :param:) — keep the description.
  const tagIdx = s.search(/\n\s*(@\w+|:\w+:)/);
  if (tagIdx > 0) s = s.slice(0, tagIdx);

  // First paragraph only, whitespace collapsed.
  s = s.split(/\n\s*\n/)[0].replace(/\s+/g, " ").trim();
  if (s.length < 3) return undefined;
  if (DOC_NOISE.test(s)) return undefined;

  if (s.length > MAX_DOC) {
    s = s.slice(0, MAX_DOC).replace(/\s+\S*$/, "").trim() + "…";
  }
  return s || undefined;
}

// Parse a triple-quoted string starting at lines[startIdx] (0-based). Returns the raw
// inner text, or undefined if that line does not open one. Handles single- and
// multi-line forms and optional string prefixes (r/b/u).
function parseTripleQuoted(lines: string[], startIdx: number): string | undefined {
  const line = lines[startIdx];
  const open = /^\s*[rRbBuUfF]{0,2}("""|''')/.exec(line);
  if (!open) return undefined;
  const quote = open[1];
  const afterOpen = line.slice(line.indexOf(quote) + 3);
  const sameLineClose = afterOpen.indexOf(quote);
  if (sameLineClose >= 0) return afterOpen.slice(0, sameLineClose);

  const collected: string[] = [afterOpen];
  for (let j = startIdx + 1; j < lines.length && j < startIdx + 60; j++) {
    const close = lines[j].indexOf(quote);
    if (close >= 0) {
      collected.push(lines[j].slice(0, close));
      break;
    }
    collected.push(lines[j]);
  }
  return collected.join("\n");
}

/**
 * A contiguous comment block immediately above a declaration: line comments (`//`,
 * `///`, `#`, `--`) or a JSDoc/C block comment. Decorator/annotation lines directly
 * above the declaration are skipped so the doc that sits above them is still found.
 * `startLine1` is 1-based.
 */
export function leadingCommentDoc(text: string, startLine1: number): string | undefined {
  const lines = text.split("\n");
  let i = startLine1 - 2; // line directly above the declaration (0-based)
  while (i >= 0 && /^\s*@[\w.]/.test(lines[i])) i--; // skip decorators/annotations
  if (i < 0) return undefined;

  const line = lines[i];
  // Block comment ending on this line — walk up to its opener.
  if (/\*\/\s*$/.test(line)) {
    const collected: string[] = [];
    for (let j = i; j >= 0 && j > i - 60; j--) {
      collected.unshift(lines[j]);
      if (/\/\*/.test(lines[j])) return normalizeDoc(collected.join("\n"));
    }
    return undefined;
  }
  // Contiguous single-line comments.
  const isLineComment = (l: string) => /^\s*(\/\/\/?|#+|--+)/.test(l);
  if (!isLineComment(line)) return undefined;
  const collected: string[] = [];
  let j = i;
  while (j >= 0 && isLineComment(lines[j])) {
    collected.unshift(lines[j]);
    j--;
  }
  return normalizeDoc(collected.join("\n"));
}

/**
 * The docstring inside a Python `def`/`class` body. `startLine1` is the 1-based line
 * of the `def`/`class` header (its signature may span several lines).
 */
export function pythonDocstring(text: string, startLine1: number): string | undefined {
  const lines = text.split("\n");
  let i = startLine1 - 1; // 0-based header line
  // Advance past a possibly multi-line signature to the line after the colon.
  for (let guard = 0; i < lines.length && guard < 50; guard++, i++) {
    if (/:\s*(#.*)?$/.test(lines[i])) {
      i++;
      break;
    }
  }
  while (i < lines.length && lines[i].trim() === "") i++;
  if (i >= lines.length) return undefined;
  const raw = parseTripleQuoted(lines, i);
  return raw === undefined ? undefined : normalizeDoc(raw);
}

/**
 * A module-level summary: a leading Python module docstring, or a top-of-file comment
 * block (after an optional shebang). Returns undefined when the file opens with code.
 */
export function moduleDoc(text: string): string | undefined {
  const lines = text.split("\n");
  let i = 0;
  if (lines[i]?.startsWith("#!")) i++; // shebang
  // coding declarations / blank lines
  while (i < lines.length && (lines[i].trim() === "" || /coding[:=]/.test(lines[i]))) i++;
  if (i >= lines.length) return undefined;

  const tq = parseTripleQuoted(lines, i);
  if (tq !== undefined) return normalizeDoc(tq);

  if (/^\s*(\/\/\/?|#+|--+|\/\*)/.test(lines[i])) {
    return leadingCommentDoc(text, i + 2); // treat as a decl on the line after the comment
  }
  return undefined;
}
